---
title: "AR case"
author: "Xiaotian Jin"
date: "7/8/2021"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
load_all()
```

# AR case 

AR case - AR(1) process with NIG noise and guassian measurement error.

## generate sample

```{r}
alpha <- 0.5

n_obs <- 1000
mu <- 1
delta <- -mu
eta <- nu <-  0.5
sigma <- 1
sigma_eps <-  1

trueV <- ngme2::rig(n_obs, nu, nu) 
noise <- delta + mu*trueV + sigma * sqrt(trueV) * rnorm(n_obs)

trueW <- Reduce(function(x,y){y + alpha*x}, noise, accumulate = T)
Y <- trueW + rnorm(n_obs, mean=0, sd=sqrt(sigma_eps))

ts.plot(Y)
```

```{r}
library(Matrix)
C <- Matrix(diag(n_obs)); 
C <- as(C, "dgCMatrix"); 

G <- Matrix(0, n_obs, n_obs)
G[seq(2, n_obs*n_obs, by=n_obs+1)] <- -1
G <- as(G, "dgCMatrix"); 

A <- as(Matrix(diag(n_obs)), "dgCMatrix"); 


K_func <- function(a) {C + a*G}
dK <- C; 
d2K <- 0 * C;
```



```{r}

grad_func <- function(a, V,  W){
  K <- K_func(a)
  g <- sum(diag(dK %*% solve(K))) - 
           t(W) %*% t(dK) %*% diag(1/V) %*% (K %*% W + (1-V)*mu)
  as.double(g)
}

# grad_func(0.5, trueV, trueW)

gd <- function(a_init) {
  a <- a_init
  for (iter in 1:10) {
    g <- grad_func(a, trueV, trueW)
    a = a - 0.00005 * g
    print(a)
  }
  a
}

gd(5)s
```


## gibbs_sample

```{r}
gibbs_sample <- function(K, A, alpha, N_sim, V_init, W_init) {
  n <- n_obs
  V <- V_init
  
  W <- W_init
  
  # Vector of conditional means E[w|V,Y]
  m_W <- matrix(0, nrow=1, ncol=n_obs)
  
  # Gibbs sampling
   K_alpha <- diag(n)
   K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  
   eta <- nu
   
  for(i in 1:N_sim){
    Q <- t(K_alpha) %*% diag(1/V[i,]) %*% K_alpha / sigma^2
    
    resp <- Q %*% forwardsolve(K_alpha, (-1 + V[i,])*mu) + t(A_matrix) %*% Y / sigma_eps^2
    
    m_W <- rbind(m_W, t(solve(Q + Asq, resp)))
    
    Prec <- K_alpha%*%diag(1/V[i,])%*%K_alpha + Asq
    
    Chol <- chol(Q + Asq)
    
    W <- rbind(W, m_W[i+1,] + t(solve(Chol, rnorm(n_obs))))
    V <- rbind(V, ngme2::rgig(n_obs, 
                             -1, 
                             eta + (mu/sigma)^2, 
                             eta +
                             as.vector((K_alpha%*%W[i+1,] +1)^2)/sigma^2))
  }
   
  return(list(W = W[2:(N_sim+1),], V = V[2:(N_sim+1),], m_W = m_W[2:(N_sim+1),]))
}
```

## grad_desc

```{r}

grad_alpha <- function(alpha, V,  W){
  n <- n_obs
  K_alpha <- diag(n)
  K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  K_diff <-matrix(data=0, nrow=n, ncol=n)
  K_diff[seq(2, n*n, by=n+1)] <- -1
  return(sum(diag(solve(as.matrix(K_alpha),K_diff))) - 
           t(W) %*% K_diff %*%diag(1/V)%*%(K_alpha%*%W+(1-V)*mu))
}

grad_alpha_rb <- function(alpha, V){
  n <- n_obs
  K_alpha <- diag(n)
  K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  K_diff <-matrix(data=0, nrow=n, ncol=n)
  K_diff[seq(2, n*n, by=n+1)] <- -1
  Q <- t(K_alpha)%*%diag(1/V)%*%K_alpha
  m <- forwardsolve(K_alpha, -1 + V, upper.tri =F)
  Q_tilde <- Q + Asq
  m_tilde <- solve(Q_tilde, Q%*%m + t(A_matrix)%*%Y)
  return(sum(diag(solve(as.matrix(K_alpha),K_diff))) - 
           sum(diag(solve(Q_tilde,t(K_diff)%*%diag(1/V)%*%K_alpha)))-
           t(m_tilde)%*%t(K_diff) %*%diag(1/V)%*%K_alpha%*%m_tilde - 
           t(m_tilde)%*%t(K_diff)%*%diag(1/V)%*%(1-V)*mu)
}

hess_alpha <- function(alpha, V,  W){
  n = n_obs
  K_alpha <- diag(n)
  K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  K_diff <-matrix(data=0, nrow=n, ncol=n)
  K_diff[seq(2, n*n, by=n+1)] <- -1
  
  M <- solve(as.matrix(K_alpha),K_diff)
  
  Q <- t(K_alpha)%*%diag(1/V)%*%K_alpha
  m <- solve(K_alpha, -1 + V)
  Q_tilde <- Q + Asq
  m_tilde <- solve(Q_tilde, Q%*%m + t(A_matrix)%*%Y)
  
  dQ <- 1/sigma * (t(K_diff) %*%diag(1/V)%*%K_alpha + 
                      t(K_alpha)%*%diag(1/V)%*%K_diff)
  
  temp <- dQ%*%m - Q%*%forwardsolve(K_alpha,K_diff, upper.tri = F) %*% forwardsolve(K_alpha,-1 + V,upper.tri = F)
  
  Q_t_inv <- solve(Q_tilde)
  
  dm_tilde <- -Q_t_inv%*%dQ%*%
    Q_t_inv%*%(Q%*%m + sigma_eps^(-2)*t(A_matrix)%*%Y) +
    Q_t_inv%*%temp
  
  term1 <- -sum(diag(M%*%M))
  term2 <- sum(diag(t(K_diff)%*%diag(1/V)%*%K_diff%*%Q_t_inv)) -
    sum(diag(t(K_diff)%*%diag(1/V)%*%K_alpha%*%Q_t_inv%*%dQ%*%Q_t_inv))
  term3 <- t(dm_tilde)%*%t(K_diff)%*%diag(1/V)%*%K_alpha%*%m_tilde +
    t(m_tilde)%*%t(K_diff)%*%diag(1/V)%*%K_diff%*%m_tilde +
    t(m_tilde)%*%t(K_diff)%*%diag(1/V)%*%K_alpha%*%dm_tilde
  term4 <- t(dm_tilde)%*%t(K_diff)%*%diag(1/V)%*%(1-V)
  
  return(term1-term2-term3-term4)
}

```


## overall process

```{r}
epsilon <- 10^{-5}
tol = 1

alpha_est <- 0
alpha_list <- alpha_est

n = 1

#Gibbs sample sizes
gibbs_nsim <- 10

V_init <- matrix(ngme2::rig(n_obs, eta, eta), nrow=1)
W_init <- matrix(0, nrow=1, ncol=n_obs)

#Burn in for the first one
list_VW <- gibbs_sample(f1$K(alpha_est), f1$A, alpha_est, 300, V_init, W_init)

V_init <- matrix(list_VW[["V"]][gibbs_nsim,],nrow=1)
W_init <- matrix(list_VW[["W"]][gibbs_nsim,],nrow=1)

previous_Gibbs <- list_VW
switch_hessian <- FALSE

while(tol > epsilon){
  temp <- alpha_est
  
  list_VW <- gibbs_sample(f1$K(alpha_est), f1$A, alpha_est, gibbs_nsim, V_init, W_init)
  V_matrix <- list_VW[["V"]]
  W_matrix <- list_VW[["W"]]
  
  V_init <- matrix(V_matrix[gibbs_nsim,],nrow=1)
  W_init <- matrix(W_matrix[gibbs_nsim,],nrow=1)
  
  grad_k_V <- sapply(1:(gibbs_nsim), function(i){
    grad_alpha_rb(alpha_est, as.vector(V_matrix[i,]))[1,1]
  })
  
  grad_alpha_est <- mean(grad_k_V)
    
    #Computing the hessian for the previous Gibbs sample
    previous_V <- previous_Gibbs[["V"]]
    previous_W <- previous_Gibbs[["W"]]
    hess_alpha_est_V <- sapply(1:(gibbs_nsim), function(i){
      hess_alpha(alpha_est, as.vector(previous_V[i,]), 
                 as.vector(previous_W[i,]))[1,1] 
    })
  
  I_kappa <- -mean(hess_alpha_est_V)
  alpha_est = alpha_est + grad_alpha_est/I_kappa * n^{-1}
  
  print(alpha_est)
  
  alpha_list <- c(alpha_list, alpha_est)
  tol <- sqrt(sum((alpha_est-temp)^2))
  n = n+1
  previous_Gibbs <- list_VW
}

```

```{r}
opt <- function(epsilon=10^(-5), tol=1, alpha_init=0, K, A, eta) {
  
  alpha_est <- alpha_init
  alpha_list <- alpha_est
  n_obs <- nrow(A)
  n = 1
  
  #Gibbs sample sizes
  gibbs_nsim <- 10
  V_init <- matrix(ngme2::rig(n_obs, eta, eta), nrow=1)
  W_init <- matrix(0, nrow=1, ncol=n_obs)
  
  #Burn in for the first one
  list_VW <- gibbs_sample(K, A, alpha_est, 300, V_init, W_init)
  V_init <- matrix(list_VW[["V"]][gibbs_nsim,], nrow=1)
  W_init <- matrix(list_VW[["W"]][gibbs_nsim,], nrow=1)
  
  previous_Gibbs <- list_VW
  switch_hessian <- FALSE
  
  while(tol > epsilon){
    temp <- alpha_est
    
    list_VW <- gibbs_sample(K, A, alpha_est, gibbs_nsim, V_init, W_init)
    V_matrix <- list_VW[["V"]]
    W_matrix <- list_VW[["W"]]
    
    V_init <- matrix(V_matrix[gibbs_nsim,],nrow=1)
    W_init <- matrix(W_matrix[gibbs_nsim,],nrow=1)
    
    grad_k_V <- sapply(1:(gibbs_nsim), function(i){
      grad_alpha_rb(alpha_est, as.vector(V_matrix[i,]))[1,1]
    })
    
    grad_alpha_est <- mean(grad_k_V)
      
      #Computing the hessian for the previous Gibbs sample
      previous_V <- previous_Gibbs[["V"]]
      previous_W <- previous_Gibbs[["W"]]
      hess_alpha_est_V <- sapply(1:(gibbs_nsim), function(i){
        hess_alpha(alpha_est, as.vector(previous_V[i,]), 
                   as.vector(previous_W[i,]))[1,1] 
      })
    
    I_kappa <- -mean(hess_alpha_est_V)
    alpha_est = alpha_est + grad_alpha_est/I_kappa * n^{-1}
    
    print(alpha_est)
    
    alpha_list <- c(alpha_list, alpha_est)
    tol <- sqrt(sum((alpha_est-temp)^2))
    n = n+1
    previous_Gibbs <- list_VW
  }
}

opt(epsilon=10^(-5), tol=1, alpha_init=0, K=f1$K(alpha_est), A=f1$A, eta=eta)
```


