---
title: "AR case"
author: "Xiaotian Jin"
date: "7/8/2021"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
load_all() 
set.seed(777)
```

# AR case 

AR case - AR(1) process with NIG noise and guassian measurement error.

## generate sample

```{r}
alpha <- 0.7
n_obs <- 1000
mu <- 1

eta <- nu <-  0.9
sigma <- 1
sigma_eps <-  1
h <- rep(1, n_obs)

gen_ar_nig <- function(alpha, n_obs, mu, sigma, nu, sigma_eps) {
  delta <- -mu
  h <- rep(1, n_obs)
  
  trueV <- ngme2::rig(n_obs, nu, nu) 
  noise <- delta + mu*trueV + sigma * sqrt(trueV) * rnorm(n_obs)
  
  trueW <- Reduce(function(x,y){y + alpha*x}, noise, accumulate = T)
  Y <- trueW + rnorm(n_obs, mean=0, sd=sqrt(sigma_eps))
  
  ts.plot(Y)
  
  library(Matrix)
  G <- Matrix(diag(n_obs)); 
  G <- as(G, "dgCMatrix"); 
  
  C <- Matrix(0, n_obs, n_obs)
  C[seq(2, n_obs*n_obs, by=n_obs+1)] <- -1
  C <- as(C, "dgCMatrix"); 
  
  A <- as(Matrix(diag(n_obs)), "dgCMatrix"); 
  
  K_func <- function(a) {a*C + G}
  
  dK <- C;
  d2K <- 0 * C;
  
  return (list(Y=Y, trueV=trueV, trueW=trueW, A=A, K=K_func, dK=dK, d2K=d2K))
}

ar1 <- gen_ar_nig(alpha, n_obs, mu, sigma, nu, sigma_eps)

Y=ar1$Y; trueV=ar1$trueV; trueW=ar1$trueW; A=ar1$A; K_func=ar1$K; dK=ar1$dK; d2K=ar1$d2K;
```

numerical dK

```{r}
dK_func <- function(a, eps) {
  (K_func(a+eps) - K_func(a)) / eps
}
dK_func(1, 0.05)
```

change of variable

```{r}
th2a <- function(th) {
  a = -1 + 2*exp(th)/(1+exp(th))
  a
}
th2a(0.24)

a2th <- function(a) {
  th = log((-1-a)/(-1+a))
  th
}
a2th(0.5) # 1.098612
```



grad of mu

```{r}
grad_mu <- function(mu, V, W) {
  K <- K_func(alpha)
  m <- solve(K, mu*(-h + V))
  
  g = sigma_eps^(-2) * t(A %*% (m/mu)) %*% diag(1/V) %*% (Y - A %*% m - A %*% (W-m))
  as.double(-(g)/n_obs)
}

grad_mu(1, trueV, trueW)
grad_mu(2, trueV, trueW)
grad_mu(3, trueV, trueW)
```

# grad mu rb

```{r}
grad_mu_rb <- function(mu, V, W) {
  K <- K_func(alpha)
  
  m <- solve(K, mu*(-h + V))
  Q <- sigma^(-2) * t(K) %*% diag(1/V) %*% K
  
  QQ <- Q + sigma_eps^(2) * t(A) %*% A
  
  mm <- solve(QQ, t(K) %*% diag(1/V) %*% (mu*V - mu*h) + sigma_eps^(2) * t(A) %*% Y)
  
  tmp = A %*% solve(K, V-h)
  g = t(tmp) %*% diag(1/V) %*% (Y - mu*tmp - A %*% (mm-m))
  as.double(-g/n_obs)
}
grad_mu_rb(1, trueV, trueW)
grad_mu_rb(2, trueV, trueW)
grad_mu_rb(3, trueV, trueW)
```


```{r}
gd_mu <- function(mu_init) {
  mu <- mu_init
  for (iter in 1:30) {
    g <- grad_mu(mu, trueV, trueW)
    mu = mu + 0.001 * g
    print(g)
  }
  mu
}

gd_mu(2)
```

grad_nu

```{r}
est_nu <- function(V) {
  print(1/( sum(1/V) / n_obs - sum(V) / n_obs + 1 ))
  1/(mean(V) + mean(1/V) - 2)
}
est_nu(trueV)


```

grad of sigma

```{r}
grad_sigma <- function(sigma, V, W, mu) {
  K <- K_func(alpha)
  mm = (K %*% W + (h-V) * mu) 
  
  g = -n_obs * log(sigma) + sigma^(-3) * t(mm) %*% diag(1/V) %*% mm
  return (as.double(g) / n_obs)
}
grad_sigma(sigma-0.5, trueV, trueW, mu)
grad_sigma(sigma, trueV, trueW, mu)
grad_sigma(sigma+0.5, trueV, trueW, mu)
```


GD

```{r}
gd_a <- function(a_init) {
  a <- a_init
  for (iter in 1:30) {
    g <- grad_a(a, trueV, trueW)
    a = a - 0.05 * g
    print(a)
  }
  a
}

gd_th <- function(th_init) {
  th <- th_init
  for (iter in 1:30) {
    g <- grad_th(th, trueV, trueW)
    th = th - 0.5 * g
    print(th)
  }
  th2a(th)
}

gd_a(3)
gd_th(3)
```

It converged!

# Gibbs sampling 


```{r}
# sample N(0, Q^-1) Q is SPD matrix 
sampleMVN <- function(Q) {
  n <- nrow(Q)
  # Q=LLT
  LT <- chol(Q)
  
  # sample Z~N(0, I)
  z <- rnorm(n)
  
  # Solve LT v = Z
  v <- forwardsolve(LT, z)
  v
}

# test sampleV
# ans <- rep(0, 5)
# for (i in 1:1000) {
#   ans = ans + sampleMVN(diag(5))  
# }
# ans / 100

# from LME paper equation (15)
# Problem: Not always SPD matrix???
sampleW_V <- function(mu, h, V, K) {
  Q <- t(K) %*% diag(1/V) %*% K
  m <- solve(K, (-mu* h + mu*V)) 
  
  as.vector(m + sampleMVN(Q))
}
# test
sampleW_V(mu, h=h, trueV, K_func(0.5))

### version 1
# sampleW_VY <- function(mu, h, V, K, Y, sigma, sigma_eps, A) {
#   m <- solve(K, (-mu* h + mu*V))
#   Q <- sigma^(-2) * t(K) %*% diag(1/V) %*% K
#   
#   QQ <- Q + sigma_eps^(2) * t(A) %*% A
#   mm <- solve(QQ, Q %*% m + sigma_eps^(2) * t(A) %*% Y)
#   
#   as.vector(mm + sampleMVN(QQ))
# }


### Question : what is mu and sigma in multi. var. case
### version 2. from tutorial 2. page 7 last equation
sampleW_VY <- function(mu, h, V, K, Y, sigma, sigma_eps, A) {
  m <- solve(K, mu*(-h + V))
  Q <- sigma^(-2) * t(K) %*% diag(1/V) %*% K
  
  QQ <- Q + sigma_eps^(2) * t(A) %*% A
  
  mm <- solve(QQ, t(K) %*% diag(1/V) %*% (mu*V - mu*h) + sigma_eps^(2) * t(A) %*% Y)
  # mm <- solve(QQ, Q %*% m + sigma_eps^(2) * t(A) %*% Y)
  # mm <- solve(QQ, Q %*% forwardsolve(K, (-h+V)*mu) + sigma_eps^(2) * t(A) %*% Y)
  
  as.vector(mm + sampleMVN(QQ))
}

# test
sampleW_VY(mu, h=h, trueV, K_func(1.5), Y, sigma, sigma_eps, A)


# tutorial 2. page 3
sampleV_WY <- function(n, p, a, b, mu, sigma, h, K, W) {
  p = rep(p - 0.5, n)
  a = rep(a + (mu/sigma)^2, n)
  b = b + (1/sigma)^2 * (K%*%W + mu*h)^2
  b = as.vector(b)
  ngme2::rgig(n,p,a,b)
  # return(list(a=a,b=b,p=p))
}
# test
# ngme2::rgig(10, -0.5, 0.4, 100)
sampleV_WY(n_obs, p=-0.5, a=nu, b=nu, mu=mu, sigma=sigma, h=h, K=K_func(0.5), trueW)
```

# sgd using gibbs samples

```{r}
gd_gibbs <- function(a_init, V_init, stepsize) {
  a <- a_init
  V <- V_init
  n_sample <- 50
  for (iter in 1:30) {
    g <- 0
    K <- K_func(a)
    for (sample in 1:n_sample) {
        
      # print(list(mu, h, V, K, Y, sigma, sigma_eps, A))
      W <- sampleW_VY(mu, h, V, K, Y, sigma, sigma_eps, A)
      V <- sampleV_WY(n_obs, p=-0.5, a=nu, b=nu, mu=mu, sigma=sigma, h=h, K=K, W)
      
      g <- g + grad_func(a, V, W)
      # g <- g + grad_func(a, trueV, trueW)
    }
    g <- g/n_sample
    a = a - stepsize * g
    print(paste("a=", round(a,3)))
    print(paste("grad=", round(g,3)))
  }
  return (a)
}

V_init <- rep(1, n_obs)
gd_gibbs(0.5, trueV, stepsize=0.1)
```

```{r}
grad_func(0.5, trueV, trueW)

# grad_func(0.5, trueV, trueW)
# gibbs sampling
for (i in 1:100) {
  W <- sampleW_VY(mu, h, V, K, Y, sigma, sigma_eps, A)
}
```

test convergence with gibbs using trueW or trueV

```{r}
gd_gibbs <- function(a_init, V_init, stepsize) {
  a <- a_init
  V <- V_init
  n_sample <- 50
  for (iter in 1:30) {
    g <- 0
    K <- K_func(a)
    for (sample in 1:n_sample) {
        
    # use trueV (seems underestimate a, maybe wrong with W?)
      W <- sampleW_VY(mu, h, trueV, K, Y, sigma, sigma_eps, A)
      g <- g + grad_func(a, trueV, W)
      
    # use trueW
      V <- sampleV_WY(n_obs, p=-0.5, a=nu, b=nu, mu=mu, sigma=sigma, h=h, K=K, trueW)
      g <- g + grad_func(a, V, trueW)
      
      # g <- g + grad_func(a, trueV, trueW)
    }
    
    g <- g/n_sample
    a = a - stepsize * g
    
    print(paste("a=", round(a,3)))
    print(paste("grad=", round(g,3)))
  }
  return (a)
}

V_init <- rep(1, n_obs)
gd_gibbs(3, V_init, stepsize=0.05)
```

```{r}

# grad_rb_func <- function(a, V){
#   n <- n_obs
#   K <- K_func(a)
#   K_diff <-matrix(data=0, nrow=n, ncol=n)
#   K_diff[seq(2, n*n, by=n+1)] <- -1
#   
#   Q <- t(K)%*%diag(1/V)%*%K
#   m <- forwardsolve(K, -1 + V, upper.tri =F)
#   Q_tilde <- Q + Asq
#   m_tilde <- solve(Q_tilde, Q%*%m + t(A_matrix)%*%Y)
#   return(sum(diag(solve(as.matrix(K),K_diff))) - 
#            sum(diag(solve(Q_tilde,t(K_diff)%*%diag(1/V)%*%K)))-
#            t(m_tilde)%*%t(K_diff) %*%diag(1/V)%*%K%*%m_tilde - 
#            t(m_tilde)%*%t(K_diff)%*%diag(1/V)%*%(1-V)*mu)
# }

# grad_func(0.5, trueV, trueW)

gd <- function(a_init) {
  a <- a_init
  for (iter in 1:30) {
    g <- grad_func(a, trueV, trueW)
    a = a - 0.0005 * g
    print(a)
  }
  a
}

gd(5)
```


```{r}
hess_func <- function(a, V,  W){
  Asq <- t(A_matrix) %*% A_matrix / sigma_eps^2
  n = n_obs
  K <- K_func(a)
  
  M <- solve(as.matrix(K),dK)
  
  Q <- t(K)%*%diag(1/V)%*%K
  m <- solve(K, -1 + V)
  Q_tilde <- Q + Asq
  m_tilde <- solve(Q_tilde, Q%*%m + t(A_matrix)%*%Y)
  
  dQ <- 1/sigma * (t(dK) %*%diag(1/V)%*%K + 
                      t(K)%*%diag(1/V)%*%dK)
  
  temp <- dQ%*%m - Q%*%forwardsolve(K,dK, upper.tri = F) %*% forwardsolve(K,-1 + V,upper.tri = F)
  
  Q_t_inv <- solve(Q_tilde)
  
  dm_tilde <- -Q_t_inv%*%dQ%*%
    Q_t_inv%*%(Q%*%m + sigma_eps^(-2)*t(A_matrix)%*%Y) +
    Q_t_inv%*%temp
  
  term1 <- -sum(diag(M%*%M))
  term2 <- sum(diag(t(dK)%*%diag(1/V)%*%dK%*%Q_t_inv)) -
    sum(diag(t(dK)%*%diag(1/V)%*%K%*%Q_t_inv%*%dQ%*%Q_t_inv))
  term3 <- t(dm_tilde)%*%t(dK)%*%diag(1/V)%*%K%*%m_tilde +
    t(m_tilde)%*%t(dK)%*%diag(1/V)%*%dK%*%m_tilde +
    t(m_tilde)%*%t(dK)%*%diag(1/V)%*%K%*%dm_tilde
  term4 <- t(dm_tilde)%*%t(dK)%*%diag(1/V)%*%(1-V)
  
  return(term1-term2-term3-term4)
}

hess_func(1.5, trueV, trueW)

```


## gibbs_sample

```{r}
gibbs_sample <- function(K, A, alpha, N_sim, V_init, W_init) {
  n <- n_obs
  V <- V_init
  
  W <- W_init
  
  # Vector of conditional means E[w|V,Y]
  m_W <- matrix(0, nrow=1, ncol=n_obs)
  
  # Gibbs sampling
   K_alpha <- diag(n)
   K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  
   eta <- nu
   
  for(i in 1:N_sim){
    Q <- t(K_alpha) %*% diag(1/V[i,]) %*% K_alpha / sigma^2
    
    resp <- Q %*% forwardsolve(K_alpha, (-1 + V[i,])*mu) + t(A_matrix) %*% Y / sigma_eps^2
    
    m_W <- rbind(m_W, t(solve(Q + Asq, resp)))
    
    Prec <- K_alpha%*%diag(1/V[i,])%*%K_alpha + Asq
    
    Chol <- chol(Q + Asq)
    
    W <- rbind(W, m_W[i+1,] + t(solve(Chol, rnorm(n_obs))))
    V <- rbind(V, ngme2::rgig(n_obs, 
                             -1, 
                             eta + (mu/sigma)^2, 
                             eta +
                             as.vector((K_alpha%*%W[i+1,] +1)^2)/sigma^2))
  }
   
  return(list(W = W[2:(N_sim+1),], V = V[2:(N_sim+1),], m_W = m_W[2:(N_sim+1),]))
}
```

## grad_desc

```{r}

grad_alpha <- function(alpha, V,  W){
  n <- n_obs
  K_alpha <- diag(n)
  K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  K_diff <-matrix(data=0, nrow=n, ncol=n)
  K_diff[seq(2, n*n, by=n+1)] <- -1
  return(sum(diag(solve(as.matrix(K_alpha),K_diff))) - 
           t(W) %*% K_diff %*%diag(1/V)%*%(K_alpha%*%W+(1-V)*mu))
}

grad_alpha_rb <- function(alpha, V){
  n <- n_obs
  K_alpha <- diag(n)
  K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  K_diff <-matrix(data=0, nrow=n, ncol=n)
  K_diff[seq(2, n*n, by=n+1)] <- -1
  Q <- t(K_alpha)%*%diag(1/V)%*%K_alpha
  m <- forwardsolve(K_alpha, -1 + V, upper.tri =F)
  Q_tilde <- Q + Asq
  m_tilde <- solve(Q_tilde, Q%*%m + t(A_matrix)%*%Y)
  return(sum(diag(solve(as.matrix(K_alpha),K_diff))) - 
           sum(diag(solve(Q_tilde,t(K_diff)%*%diag(1/V)%*%K_alpha)))-
           t(m_tilde)%*%t(K_diff) %*%diag(1/V)%*%K_alpha%*%m_tilde - 
           t(m_tilde)%*%t(K_diff)%*%diag(1/V)%*%(1-V)*mu)
}

hess_alpha <- function(alpha, V,  W){
  n = n_obs
  K_alpha <- diag(n)
  K_alpha[seq(2, n*n, by=n+1)] <- -alpha
  K_diff <-matrix(data=0, nrow=n, ncol=n)
  K_diff[seq(2, n*n, by=n+1)] <- -1
  
  M <- solve(as.matrix(K_alpha),K_diff)
  
  Q <- t(K_alpha)%*%diag(1/V)%*%K_alpha
  m <- solve(K_alpha, -1 + V)
  Q_tilde <- Q + Asq
  m_tilde <- solve(Q_tilde, Q%*%m + t(A_matrix)%*%Y)
  
  dQ <- 1/sigma * (t(K_diff) %*%diag(1/V)%*%K_alpha + 
                      t(K_alpha)%*%diag(1/V)%*%K_diff)
  
  temp <- dQ%*%m - Q%*%forwardsolve(K_alpha,K_diff, upper.tri = F) %*% forwardsolve(K_alpha,-1 + V,upper.tri = F)
  
  Q_t_inv <- solve(Q_tilde)
  
  dm_tilde <- -Q_t_inv%*%dQ%*%
    Q_t_inv%*%(Q%*%m + sigma_eps^(-2)*t(A_matrix)%*%Y) +
    Q_t_inv%*%temp
  
  term1 <- -sum(diag(M%*%M))
  term2 <- sum(diag(t(K_diff)%*%diag(1/V)%*%K_diff%*%Q_t_inv)) -
    sum(diag(t(K_diff)%*%diag(1/V)%*%K_alpha%*%Q_t_inv%*%dQ%*%Q_t_inv))
  term3 <- t(dm_tilde)%*%t(K_diff)%*%diag(1/V)%*%K_alpha%*%m_tilde +
    t(m_tilde)%*%t(K_diff)%*%diag(1/V)%*%K_diff%*%m_tilde +
    t(m_tilde)%*%t(K_diff)%*%diag(1/V)%*%K_alpha%*%dm_tilde
  term4 <- t(dm_tilde)%*%t(K_diff)%*%diag(1/V)%*%(1-V)
  
  return(term1-term2-term3-term4)
}

```


## overall process

```{r}
epsilon <- 10^{-5}
tol = 1

alpha_est <- 0
alpha_list <- alpha_est

n = 1

#Gibbs sample sizes
gibbs_nsim <- 10

V_init <- matrix(ngme2::rig(n_obs, eta, eta), nrow=1)
W_init <- matrix(0, nrow=1, ncol=n_obs)

#Burn in for the first one
list_VW <- gibbs_sample(f1$K(alpha_est), f1$A, alpha_est, 300, V_init, W_init)

V_init <- matrix(list_VW[["V"]][gibbs_nsim,],nrow=1)
W_init <- matrix(list_VW[["W"]][gibbs_nsim,],nrow=1)

previous_Gibbs <- list_VW
switch_hessian <- FALSE

while(tol > epsilon){
  temp <- alpha_est
  
  list_VW <- gibbs_sample(f1$K(alpha_est), f1$A, alpha_est, gibbs_nsim, V_init, W_init)
  V_matrix <- list_VW[["V"]]
  W_matrix <- list_VW[["W"]]
  
  V_init <- matrix(V_matrix[gibbs_nsim,],nrow=1)
  W_init <- matrix(W_matrix[gibbs_nsim,],nrow=1)
  
  grad_k_V <- sapply(1:(gibbs_nsim), function(i){
    grad_alpha_rb(alpha_est, as.vector(V_matrix[i,]))[1,1]
  })
  
  grad_alpha_est <- mean(grad_k_V)
    
    #Computing the hessian for the previous Gibbs sample
    previous_V <- previous_Gibbs[["V"]]
    previous_W <- previous_Gibbs[["W"]]
    hess_alpha_est_V <- sapply(1:(gibbs_nsim), function(i){
      hess_alpha(alpha_est, as.vector(previous_V[i,]), 
                 as.vector(previous_W[i,]))[1,1] 
    })
  
  I_kappa <- -mean(hess_alpha_est_V)
  alpha_est = alpha_est + grad_alpha_est/I_kappa * n^{-1}
  
  print(alpha_est)
  
  alpha_list <- c(alpha_list, alpha_est)
  tol <- sqrt(sum((alpha_est-temp)^2))
  n = n+1
  previous_Gibbs <- list_VW
}

```

```{r}
opt <- function(epsilon=10^(-5), tol=1, alpha_init=0, K, A, eta) {
  
  alpha_est <- alpha_init
  alpha_list <- alpha_est
  n_obs <- nrow(A)
  n = 1
  
  #Gibbs sample sizes
  gibbs_nsim <- 10
  V_init <- matrix(ngme2::rig(n_obs, eta, eta), nrow=1)
  W_init <- matrix(0, nrow=1, ncol=n_obs)
  
  #Burn in for the first one
  list_VW <- gibbs_sample(K, A, alpha_est, 300, V_init, W_init)
  V_init <- matrix(list_VW[["V"]][gibbs_nsim,], nrow=1)
  W_init <- matrix(list_VW[["W"]][gibbs_nsim,], nrow=1)
  
  previous_Gibbs <- list_VW
  switch_hessian <- FALSE
  
  while(tol > epsilon){
    temp <- alpha_est
    
    list_VW <- gibbs_sample(K, A, alpha_est, gibbs_nsim, V_init, W_init)
    V_matrix <- list_VW[["V"]]
    W_matrix <- list_VW[["W"]]
    
    V_init <- matrix(V_matrix[gibbs_nsim,],nrow=1)
    W_init <- matrix(W_matrix[gibbs_nsim,],nrow=1)
    
    grad_k_V <- sapply(1:(gibbs_nsim), function(i){
      grad_alpha_rb(alpha_est, as.vector(V_matrix[i,]))[1,1]
    })
    
    grad_alpha_est <- mean(grad_k_V)
      
      #Computing the hessian for the previous Gibbs sample
      previous_V <- previous_Gibbs[["V"]]
      previous_W <- previous_Gibbs[["W"]]
      hess_alpha_est_V <- sapply(1:(gibbs_nsim), function(i){
        hess_alpha(alpha_est, as.vector(previous_V[i,]), 
                   as.vector(previous_W[i,]))[1,1] 
      })
    
    I_kappa <- -mean(hess_alpha_est_V)
    alpha_est = alpha_est + grad_alpha_est/I_kappa * n^{-1}
    
    print(alpha_est)
    
    alpha_list <- c(alpha_list, alpha_est)
    tol <- sqrt(sum((alpha_est-temp)^2))
    n = n+1
    previous_Gibbs <- list_VW
  }
}

opt(epsilon=10^(-5), tol=1, alpha_init=0, K=f1$K(alpha_est), A=f1$A, eta=eta)
```



```{r}
n <- 7
K_alpha <- diag(n)
K_alpha[seq(2, n*n, by=n+1)] <- -alpha; K_alpha
  
K_diff <-matrix(data=0, nrow=n, ncol=n)
K_diff[seq(2, n*n, by=n+1)] <- -1; K_diff

```



