# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_cpp <- function(in_list) {
    .Call('_ngme2_estimate_cpp', PACKAGE = 'ngme2', in_list)
}

rGIG_cpp <- function(p, a, b, seed) {
    .Call('_ngme2_rGIG_cpp', PACKAGE = 'ngme2', p, a, b, seed)
}

